### ISSUE TITLE
crond can't see drive contents

### ISSUE THREAD

**Issue by Chovin** [openbridge/ob_bulkstash#11]
I've not been able to get this running with crond
Sticking some debug stuff in `rclone.sh`, shows that it can see that gdrive is a remote but it can't see its contents
```sh
...
  fi
  echo "Executing => $sync_command" >> /test
  eval "$sync_command" || send

  echo "rclone listremotes ===" >> /test
  rclone listremotes >> /test
  echo "===" >> /test
  echo "rclone ls ===" >> /test
  rclone ls gdrive: >> /test
  echo "===" >> /test

) 200>/run/rclone.lock
...
```
from the console it seems to work fine though
```
bash-4.4# rclone listremotes
2019/03/08 08:32:45 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
gdrive:
bash-4.4# rclone ls gdrive:
2019/03/08 08:33:00 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
  1560010 Getting started
bash-4.4# cat test
Executing => rclone copy --drive-shared-with-me /data GDRIVE:/Backups/testing
rclone listremotes ===
gdrive:
===
rclone ls ===
===
```

**Comment by Chovin** [comment]
Not sure if this is related to #12

**Comment by tspicer** [comment]
How are you running cron? Using ENV or a mounted cron conf file?

**Comment by Chovin** [comment]
I’m using a cron conf file. You can see the RCLONE_SYNC_COMMAND i’m using in the cat above

**Comment by tspicer** [comment]
I just tried it and I can run with crond. If you are using your own cron file, remember that cron often will not have access to the system ENV variables. You need to make sure your cron file contains the desired variables. The simplest approach might looks something like this;

```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CACHE_PREFIX={{CACHE_PREFIX}}
AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}
AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}
AWS_S3BUCKET={{AWS_S3BUCKET}}
*/45 * * * * /usr/bin/env foo -c /usr/bin/foo 2>&1
```

There are a few references around that describe cron and env variables.

**Comment by Chovin** [comment]
This is my crontab.conf
```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
*/1 * * * * /usr/bin/env bash -c "/rclone.sh run"
```
and this is my docker-compose.yml
```yml
version: '3'
services:
  rclone:
    image: openbridge/ob_bulkstash
    environment:
      - RCLONE_CONFIG_GDRIVE_TYPE=drive
      - RCLONE_CONFIG_GDRIVE_SCOPE=drive
      - RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE=auth.json
      - RCLONE_CRONFILE=/cron/crontab.conf
      - RCLONE_SYNC_COMMAND=rclone copy --drive-shared-with-me /data GDRIVE:/Backups/$DESTINATION_PATH
    volumes:
      - $DATA_PATH:/data:ro
      - $AUTH_JSON:/auth.json:ro
      - $CRONTAB_CONF_FILE:/cron/crontab.conf
    command: tail -f /dev/null 
```

what env variables would I need? Once cron runs rclone.sh, it seems to have all it needs (RCLONE_SYNCE_COMMAND). It gets the command fine. Unless I'm missing something, the behavior I'm seeing is that with cron running rclone, it does not have access to google drive contents.
